// ── ID interfaces ─────────────────────────────────────────────────────────────
// Each interface is intentionally empty by default. Augment it via
// `declare module "@drincs/nqtr/registries"` (usually from an auto-generated
// `.gen.d.ts` file written by vitePluginNqtr) to narrow the corresponding
// `*IdType` from `string` to a union of known string literals.

// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrActivityIds {}
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrCommitmentIds {}
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrLocationIds {}
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrMapIds {}
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrQuestIds {}
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — augmented by vitePluginNqtr
export interface NqtrRoomIds {}

// ── ID types ──────────────────────────────────────────────────────────────────
// Default to `string` for full backwards-compatibility. Once the corresponding
// interface has at least one key (via module augmentation), the type narrows to
// the union of those keys, giving compile-time safety for entity-id parameters.

/**
 * The type used wherever an activity ID is expected.
 *
 * - **Default** — resolves to `string` so that existing code compiles without changes.
 * - **Augmented** — when {@link NqtrActivityIds} has been extended via
 *   `declare module "@drincs/nqtr/registries"`, resolves to the union of known activity IDs.
 *
 * @example
 * ```ts
 * // nqtr.gen.d.ts (auto-generated by vitePluginNqtr)
 * declare module "@drincs/nqtr/registries" {
 *     interface NqtrActivityIds { "study": never; "cook": never; }
 * }
 * ```
 */
export type ActivityIdType = [keyof NqtrActivityIds] extends [never]
    ? string
    : keyof NqtrActivityIds;

/**
 * The type used wherever a commitment ID is expected.
 *
 * - **Default** — resolves to `string`.
 * - **Augmented** — resolves to the union of known commitment IDs once
 *   {@link NqtrCommitmentIds} has been extended.
 */
export type CommitmentIdType = [keyof NqtrCommitmentIds] extends [never]
    ? string
    : keyof NqtrCommitmentIds;

/**
 * The type used wherever a location ID is expected.
 *
 * - **Default** — resolves to `string`.
 * - **Augmented** — resolves to the union of known location IDs once
 *   {@link NqtrLocationIds} has been extended.
 */
export type LocationIdType = [keyof NqtrLocationIds] extends [never]
    ? string
    : keyof NqtrLocationIds;

/**
 * The type used wherever a map ID is expected.
 *
 * - **Default** — resolves to `string`.
 * - **Augmented** — resolves to the union of known map IDs once
 *   {@link NqtrMapIds} has been extended.
 */
export type MapIdType = [keyof NqtrMapIds] extends [never] ? string : keyof NqtrMapIds;

/**
 * The type used wherever a quest ID is expected.
 *
 * - **Default** — resolves to `string`.
 * - **Augmented** — resolves to the union of known quest IDs once
 *   {@link NqtrQuestIds} has been extended.
 */
export type QuestIdType = [keyof NqtrQuestIds] extends [never] ? string : keyof NqtrQuestIds;

/**
 * The type used wherever a room ID is expected.
 *
 * - **Default** — resolves to `string`.
 * - **Augmented** — resolves to the union of known room IDs once
 *   {@link NqtrRoomIds} has been extended.
 *
 * @example
 * ```ts
 * import type { RoomIdType } from "@drincs/nqtr/registries";
 *
 * function navigateTo(roomId: RoomIdType) { ... }
 * navigateTo("bedroom"); // ✅ compile error if "bedroom" is not a known room
 * ```
 */
export type RoomIdType = [keyof NqtrRoomIds] extends [never] ? string : keyof NqtrRoomIds;
